### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Sasha1222** [ConchbrainClub/Home#141]
Feedback Content:
how its work? 

i cant this run !

help

https://cors.conchbrain.club/?https://tc-005.agetcdn.com/1ab5d45273a9183bebb58eb74d5722d8ea6384f350caf008f08cf018f1f0566d0cb82a2a799830d1af97cd3f4b6a9a81ef3aed2fb783292b1abcf1b8560a1d1aa308008b88420298522a9f761e5aa1024fbe74e5aa853cfc933cd1219327d1232e91847a185021b184c027f97ae732b3708ee6beb80ba5db6628ced43f1196fe/7acdefb801d5ba8d961289d3a1662543/ep.12.1677598129.m3u8

**Comment by lixinyang123** [comment]
Because the server will not be streaming requests, it cannot handle requests with long response bodies.

**Comment by Sasha1222** [comment]
"it cannot handle requests with long response bodies."

What should I do?)

**Comment by lixinyang123** [comment]
You can embed videos directly in your website using the video tag, which is not limited by the CORS policy.

**Comment by Sasha1222** [comment]
can see this code? example

**Comment by lixinyang123** [comment]
no
