### ISSUE TITLE
更新推荐

### ISSUE THREAD

**Issue by lixinyang123** [ConchBrainClub/Home#28]
https://github.com/sherifabdlnaby/sched
https://github.com/morgan3d/markdeep
https://github.com/nextapps-de/winbox
https://github.com/Neoteroi/BlackSheep
https://github.com/socketio/socket.io
https://github.com/captbaritone/webamp
https://github.com/arzzen/git-quick-stats
https://github.com/dahliaOS/pangolin_desktop
https://github.com/alexmacarthur/typeit
https://github.com/nvbn/thefuck
https://github.com/prisma/prisma
https://github.com/CoenraadS/Bracket-Pair-Colorizer-2
https://github.com/ArchiveBox/ArchiveBox
https://github.com/rangav/thunder-client-support
https://github.com/micheleg/dash-to-dock
https://github.com/nemasu/asmttpd
https://github.com/hoovercj/vscode-power-mode
https://github.com/photopea/photopea
https://github.com/kimmknight/remoteapptool
https://github.com/slidevjs/slidev
https://github.com/google/zx
https://github.com/alacritty/alacritty
https://github.com/kivy/python-for-android
https://github.com/Tencent/vConsole
https://github.com/klaussinani/ao
https://github.com/tealeg/xlsx
https://github.com/tanhakabir/rest-book
https://github.com/takayama-lily/vscode-qq
https://github.com/rikukissa/typehole
https://github.com/microsoft/fast-blazor
https://github.com/schappim/macOCR
https://github.com/p-e-w/plotinus
https://github.com/withfig/autocomplete
https://github.com/shelljs/shelljs
https://github.com/dominikbraun/timetrace
https://github.com/syncthing/syncthing
https://github.com/EktoHunter/ApertureTerminal/

**Comment by ccczg** [comment]
2021/06/04
已更新
https://github.com/sherifabdlnaby/sched
https://github.com/morgan3d/markdeep
https://github.com/nextapps-de/winbox
https://github.com/Neoteroi/BlackSheep
https://github.com/socketio/socket.io
https://github.com/captbaritone/webamp
https://github.com/arzzen/git-quick-stats
https://github.com/dahliaOS/pangolin_desktop
未更新
https://github.com/alexmacarthur/typeit
https://github.com/nvbn/thefuck
https://github.com/prisma/prisma
https://github.com/CoenraadS/Bracket-Pair-Colorizer-2
https://github.com/ArchiveBox/ArchiveBox
https://github.com/rangav/thunder-client-support
https://github.com/micheleg/dash-to-dock
https://github.com/nemasu/asmttpd
https://github.com/hoovercj/vscode-power-mode
https://github.com/photopea/photopea
https://github.com/kimmknight/remoteapptool
https://github.com/slidevjs/slidev
https://github.com/google/zx
https://github.com/alacritty/alacritty
https://github.com/kivy/python-for-android
https://github.com/Tencent/vConsole
https://github.com/klaussinani/ao
https://github.com/tealeg/xlsx
https://github.com/tanhakabir/rest-book
https://github.com/takayama-lily/vscode-qq
https://github.com/rikukissa/typehole
https://github.com/microsoft/fast-blazor
https://github.com/schappim/macOCR
https://github.com/p-e-w/plotinus
https://github.com/withfig/autocomplete
https://github.com/shelljs/shelljs
https://github.com/dominikbraun/timetrace
https://github.com/syncthing/syncthing
https://github.com/EktoHunter/ApertureTerminal/

**Comment by lixinyang123** [comment]
更新 90151b563118e1dbec22644973a02cb923f5159f
https://github.com/alexmacarthur/typeit
https://github.com/nvbn/thefuck
https://github.com/prisma/prisma
https://github.com/CoenraadS/Bracket-Pair-Colorizer-2
https://github.com/ArchiveBox/ArchiveBox
https://github.com/rangav/thunder-client-support
https://github.com/micheleg/dash-to-dock
https://github.com/nemasu/asmttpd

未更新
https://github.com/hoovercj/vscode-power-mode
https://github.com/photopea/photopea
https://github.com/kimmknight/remoteapptool
https://github.com/slidevjs/slidev
https://github.com/google/zx
https://github.com/alacritty/alacritty
https://github.com/kivy/python-for-android
https://github.com/Tencent/vConsole
https://github.com/klaussinani/ao
https://github.com/tealeg/xlsx
https://github.com/tanhakabir/rest-book
https://github.com/takayama-lily/vscode-qq
https://github.com/rikukissa/typehole
https://github.com/microsoft/fast-blazor
https://github.com/schappim/macOCR
https://github.com/p-e-w/plotinus
https://github.com/withfig/autocomplete
https://github.com/shelljs/shelljs
https://github.com/dominikbraun/timetrace
https://github.com/syncthing/syncthing
https://github.com/EktoHunter/ApertureTerminal/

**Comment by lixinyang123** [comment]
已更新 15088fbc3356b7da1bf56480c8ed4daf6f8b2dfd
https://github.com/hoovercj/vscode-power-mode
https://github.com/photopea/photopea
https://github.com/kimmknight/remoteapptool
https://github.com/slidevjs/slidev
https://github.com/google/zx
https://github.com/alacritty/alacritty
https://github.com/kivy/python-for-android
https://github.com/Tencent/vConsole

未更新
https://github.com/klaussinani/ao
https://github.com/tealeg/xlsx
https://github.com/tanhakabir/rest-book
https://github.com/takayama-lily/vscode-qq
https://github.com/rikukissa/typehole
https://github.com/microsoft/fast-blazor
https://github.com/schappim/macOCR
https://github.com/p-e-w/plotinus
https://github.com/withfig/autocomplete
https://github.com/shelljs/shelljs
https://github.com/dominikbraun/timetrace
https://github.com/syncthing/syncthing
https://github.com/EktoHunter/ApertureTerminal/

**Comment by ccczg** [comment]
已全部更新完毕
